import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0A0B0E',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 90,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  profileSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#1E2230',
    borderWidth: 1,
    borderColor: '#0284C7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#FACC15',
    fontWeight: 'bold',
    fontSize: 14,
  },
  greetingText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  schoolName: {
    color: '#64748B',
    fontSize: 11,
    marginTop: 2,
  },
  weatherBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#14161F',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#1E2230',
  },
  weatherText: {
    color: '#E2E8F0',
    fontSize: 12,
    fontWeight: '600',
  },
  heroCard: {
    backgroundColor: '#14161F',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#1E2230',
    marginBottom: 24,
  },
  heroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  liveTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(2, 132, 199, 0.15)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#38BDF8',
  },
  liveTagText: {
    color: '#38BDF8',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  heroTime: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '600',
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
  },
  heroSubtitle: {
    color: '#94A3B8',
    fontSize: 12,
    marginTop: 4,
    marginBottom: 18,
  },
  heroFooter: {
    borderTopWidth: 1,
    borderTopColor: '#1E2230',
    paddingTop: 14,
  },
  primaryActionButton: {
    backgroundColor: '#FACC15',
    borderRadius: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryActionText: {
    color: '#0A0B0E',
    fontSize: 13,
    fontWeight: '700',
  },
  sectionCategory: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    marginBottom: 12,
  },
  actionsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  actionItem: {
    alignItems: 'center',
    gap: 8,
  },
  actionCircle: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#14161F',
    borderWidth: 1,
    borderColor: '#1E2230',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionLabel: {
    color: '#CBD5E1',
    fontSize: 11,
    fontWeight: '500',
  },
  cardContainer: {
    backgroundColor: '#14161F',
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: '#1E2230',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  cardHeaderTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cardTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  cardLink: {
    color: '#38BDF8',
    fontSize: 12,
    fontWeight: '600',
  },
  courtItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#1E2230',
  },
  courtBadge: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: 'rgba(2, 132, 199, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  courtBadgeText: {
    color: '#38BDF8',
    fontWeight: '800',
    fontSize: 11,
  },
  courtInfo: {
    flex: 1,
    marginLeft: 12,
  },
  courtName: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
  },
  courtDetails: {
    color: '#64748B',
    fontSize: 11,
    marginTop: 2,
  },
  tagSuccess: {
    backgroundColor: 'rgba(52, 211, 153, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  tagSuccessText: {
    color: '#34D399',
    fontSize: 11,
    fontWeight: '600',
  },
  tagWarning: {
    backgroundColor: 'rgba(250, 204, 21, 0.1)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  tagWarningText: {
    color: '#FACC15',
    fontSize: 11,
    fontWeight: '600',
  },
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 65,
    backgroundColor: '#0A0B0E',
    borderTopWidth: 1,
    borderTopColor: '#1E2230',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingBottom: 6,
  },
  navItem: {
    alignItems: 'center',
    gap: 4,
  },
  navActiveBox: {
    width: 32,
    height: 24,
    borderRadius: 10,
    backgroundColor: '#14161F',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navActiveText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '600',
  },
  navText: {
    color: '#64748B',
    fontSize: 10,
    fontWeight: '500',
  },
});